#!/usr/bin/env php

<?php

require __DIR__ . '/vendor/autoload.php';

use Lapetus\Application;
use Lapetus\Database\Migrator;

Application::configure(__DIR__);

if ($argc == 1) {
  echo "make" . PHP_EOL;
  echo "  make:migration            Create a new migration file" . PHP_EOL;
  echo PHP_EOL;

  echo "migrate" . PHP_EOL;
  echo "  migrate                   Run the database migration" . PHP_EOL;
  echo "  migrate:rollback          Rollback the last database migration" . PHP_EOL;
  echo PHP_EOL;

  return;
}

$command = $argv[1];

if ($command === "migrate") {
  $migrator = new Migrator();
  $migrator->migrate();

  return;
}

if ($command === "migrate:rollback") {
  $migrator = new Migrator();
  $migrator->rollback();

  return;
}

if ($command === "make:migration" && $argc == 3) {
  $name = $argv[2];
  $timestamp = date('Y_m_d_His');
  $stub = "lapetus/stubs/migration.stub";
  $migration = "database/migrations/{$timestamp}_{$name}.php";

  echo "Migration [{$migration}] created successfully" . PHP_EOL . PHP_EOL;

  copy($stub, $migration);

  return;
}
